# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git

RUN npm install -g pm2

WORKDIR /app
RUN git clone https://github.com/jankiz/Program-systems-development.git
WORKDIR /app/Program-systems-development
RUN git checkout release/devops

WORKDIR /app/Program-systems-development/server
RUN npm install
RUN npm run build

EXPOSE 5000 10050

RUN apk add curl

# Install Zabbix Agent
RUN apk add --no-cache \
    pcre \
    zabbix-agent2
# Configure Zabbix Agent
COPY zabbix_agent2.conf /etc/zabbix/zabbix_agent2.conf

# Install rsyslog
RUN apk add --no-cache rsyslog
# Create rsyslog config
COPY rsyslog.conf /etc/rsyslog.conf

RUN mkdir -p /var/log/pm2

# Configure PM2 to use syslog
ENV PM2_SYSLOG=true

COPY start-nodejs.sh ./start-nodejs.sh

RUN chmod +x start-nodejs.sh

CMD ["./start-nodejs.sh"]